### PR TITLE
looks good but you never know

### PR DESCRIPTION
**Pull request by Havrysh**

### CODE REVIEW

**Comment by Havrysh** [comment]
(https://havrysh.github.io/react_list-of-goods/)

**Review by ArturErmolenko — CHANGES_REQUESTED** [review]
Please add all file
Screenshot 2022-08-02 at 19 13 37
s

**Review by ArturErmolenko — CHANGES_REQUESTED** [review]
oops no changes

**Review by ArturErmolenko — CHANGES_REQUESTED** [review]
one more time)

**Review by ArturErmolenko — APPROVED** [review]
Yeap, good job 👍

**Pull request closed without merging**
